Profile content web
ansys/aedt-testing pull request #178
Opened 2022-06-27 08:39 UTC by Samuelopez-ansys

2022-06-27 15:28 UTC, Samuelopez-ansys commented
Hi @beliaev-maksim  and @boyang2022 ,

Please check this PR, I have tested it and it works for my test cases, but maybe I missed something. Bo if you see something to improve don't hesitate to modify it.

2022-06-27 16:55 UTC, beliaev-maksim commented on aedttest/aedt_test_runner.py
> +                    link = new_path
```suggestion
                assert key_name in ["mesh", "simulation_time"]
                extract = "mesh_name" if key_name == "mesh else "profile_name"

                new_path = copy_path_to(
                    design_data[extract][variation_name][setup_name], str(self.reference_profiles)
                )
                design_data["profile_name"][variation_name][setup_name] = new_path
```

2022-06-27 16:56 UTC, beliaev-maksim commented on aedttest/aedt_test_runner.py
> +                    "link": link,
```suggestion
                    "link": new_path ,
```

2022-06-27 17:00 UTC, beliaev-maksim requested changes
see comments above

2022-06-27 19:47 UTC, Samuelopez-ansys commented on aedttest/simulation_data.py
> +            design_name: {"mesh": {}, "simulation_time": {}, "report": {}, "profile_name": {}, "mesh_name": {}}
Sorry, I don't get it, what do you mean?

2022-06-28 07:22 UTC, beliaev-maksim commented on aedttest/simulation_data.py
> +            design_name: {"mesh": {}, "simulation_time": {}, "report": {}, "profile_name": {}, "mesh_name": {}}
may be it would be better to have:
design_name: {"mesh": {"mesh_name": {}}, "simulation_time": {"profile_name": {}}, "report": {}, }

2022-06-28 12:54 UTC, beliaev-maksim approved these changes

2022-06-28 12:54 UTC, merged